site_name: Guardian Accessibility and Inclusive Design
site_url: https://accessibility-gutools-co-uk.s3-eu-west-1.amazonaws.com/
repo_url: https://github.com/guardian/guardian-accessibility
site_description: Patterns and Guidelines for Accessibility and Inclusive Design at the Guardian.
pages:
  - Home: index.md
  - Patterns:
    - Alt text: 'patterns/alt-text.md'
  - Guidelines:
    - Web: 
      - HTML Lang attribute: 'guidelines/web/lang-attribute.md'
      - Use the correct HTML element: 'guidelines/web/correct-element.md'
    - Apps: 'guidelines/apps.md'
  - Testing:
    - Web:
      - Keyboard navigation: 'testing/web/keyboard-navigation.md'
      - Screen readers: 'testing/web/screen-readers.md'
theme: readthedocs
