site_name: Guardian Accessibility and Inclusive Design
site_url: https://accessibility-gutools-co-uk.s3-eu-west-1.amazonaws.com/
repo_url: https://github.com/guardian/guardian-accsesibility
site_description: Patterns and Guidelines for Accessibility and Inclusive Design at the Guardian.
pages:
  - Home: index.md
  - Patterns:
    - Example pattern: 'patterns/example-pattern.md'
  - Guidelines:
    - Web: 
      - HTML Lang attribute: 'guidelines/web/lang-attribute.md'
    - Apps: 'guidelines/apps.md'
theme: readthedocs
